/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.e;

/**
 *
 * @author edmon
 */
public class U1A1_EdmondLiang extends javax.swing.JFrame {

    /**
     * Creates new form U1A1_EdmondLiang
     */
    public U1A1_EdmondLiang() {
        initComponents();
        
        startUp();
    }
    static void startUp() {
        lablesdisappeared();
        titleLabel.setVisible(false);
        U1A1_EdmondLiang.setOpened(0);
    }
    
    static void labledisappeared() {
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonCalculate = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        txtfieldEnterCurrency = new javax.swing.JTextField();
        lblEnterCurrency = new javax.swing.JLabel();
        lblFormat = new javax.swing.JLabel();
        txtfieldAmount = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        txtfieldLoonies = new javax.swing.JTextField();
        txtfieldToonies = new javax.swing.JTextField();
        lblToonies = new javax.swing.JLabel();
        lblLoonies = new javax.swing.JLabel();
        lblDimes = new javax.swing.JLabel();
        txtfieldDimes = new javax.swing.JTextField();
        lblNickels = new javax.swing.JLabel();
        txtfieldNickels = new javax.swing.JTextField();
        lblPennies = new javax.swing.JLabel();
        txtfieldPennies = new javax.swing.JTextField();
        txtfieldQuarters = new javax.swing.JTextField();
        lblQuaters = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        buttonSiwtchtoFrame2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonCalculate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        buttonCalculate.setText("Calculate");
        buttonCalculate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCalculateActionPerformed(evt);
            }
        });

        titleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        titleLabel.setText("Change Exchange Machine");

        txtfieldEnterCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldEnterCurrencyActionPerformed(evt);
            }
        });

        lblEnterCurrency.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEnterCurrency.setText("Enter Currency:");

        lblFormat.setText("Format: (xxxx.xx)");

        txtfieldAmount.setEditable(false);
        txtfieldAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldAmountActionPerformed(evt);
            }
        });

        amountLabel.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        amountLabel.setText("Amount:");

        txtfieldLoonies.setEditable(false);
        txtfieldLoonies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldLooniesActionPerformed(evt);
            }
        });

        txtfieldToonies.setEditable(false);
        txtfieldToonies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfieldTooniesActionPerformed(evt);
            }
        });

        lblToonies.setText("Toonies:");

        lblLoonies.setText("Loonies:");

        lblDimes.setText("Dimes:");

        txtfieldDimes.setEditable(false);

        lblNickels.setText("Nickels:");

        txtfieldNickels.setEditable(false);

        lblPennies.setText("Pennies:");

        txtfieldPennies.setEditable(false);

        txtfieldQuarters.setEditable(false);

        lblQuaters.setText("Quarters:");

        buttonExit.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });

        buttonSiwtchtoFrame2.setText("Switch to multi use calculator");
        buttonSiwtchtoFrame2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSiwtchtoFrame2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblToonies)
                                .addGap(12, 12, 12)
                                .addComponent(txtfieldToonies, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblDimes)
                                .addGap(18, 18, 18)
                                .addComponent(txtfieldDimes, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblNickels)
                                .addGap(18, 18, 18)
                                .addComponent(txtfieldNickels, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(lblLoonies)
                                .addGap(18, 18, 18)
                                .addComponent(txtfieldLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblQuaters, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPennies, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfieldQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfieldPennies, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(165, 165, 165)
                                        .addComponent(amountLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtfieldAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFormat)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(76, 76, 76)
                                        .addComponent(lblEnterCurrency)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtfieldEnterCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(buttonCalculate, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonSiwtchtoFrame2)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSiwtchtoFrame2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldEnterCurrency)
                    .addComponent(lblEnterCurrency)
                    .addComponent(buttonCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFormat)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtfieldAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                            .addComponent(amountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(buttonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToonies)
                    .addComponent(txtfieldToonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldQuarters, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldLoonies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLoonies)
                    .addComponent(lblQuaters))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtfieldDimes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtfieldNickels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDimes)
                    .addComponent(txtfieldPennies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPennies)
                    .addComponent(lblNickels))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCalculateActionPerformed
        // TODO add your handling code here:
        //In case of error try sends error message instead of breaking the program
        try {
            //Getting money amount from the user
            double amountMoney = Double.parseDouble(txtfieldEnterCurrency.getText());
            txtfieldAmount.setText(Double.toString(amountMoney));

            //Temporary variable for checking if the user input is valid.
            boolean valid = false;
            //turns the double to string for check.
            String stringAmount = Double.toString(amountMoney);

            //Using the index of the . and the length of the amount, the amount of decimals can be found.
            int integerPlaces = stringAmount.indexOf(".");
            
            //To get the decimal places, you do (length of string) - (index of string) - 1
            
            int decimalPlaces =  stringAmount.length() -  integerPlaces -1;

            //Checker if amount of decimals are less than 2. If true then the currency amount is valid.
            if (decimalPlaces <= 2) {
                valid = true;
            }
            
            //If the user input is valid do, turn to coins
            if (valid) {
                double moneyAmount = amountMoney;
                //Default values in case they are not used, the coin value will be 0
                int penny = 0;
                int nickel = 0;
                int dime = 0;
                int quarter = 0;
                int loonie = 0;
                int toonie = 0;

                //Get amount toonies used by dividing, then getting the left over amount for next calculation, then resetting the glitchy format of the amount.
                toonie = (int) (moneyAmount/2.00);
                moneyAmount = moneyAmount - 2.00 * toonie;
                moneyAmount = Math.round(moneyAmount * 100.0) / 100.0;
                
                
                //Get amount loonie used by dividing, then getting the left over amount for next calculation, then resetting the format of the amount.
                loonie = (int) (moneyAmount/1);
                moneyAmount = moneyAmount - 1.00 * loonie;
                moneyAmount = Math.round(moneyAmount * 100.0) / 100.0;

                //Get amount quarter used by dividing, then getting the left over amount for next calculation, then resetting the format of the amount.
                quarter = (int) (moneyAmount/0.25);
                moneyAmount = moneyAmount - 0.25 * quarter;
                moneyAmount = Math.round(moneyAmount * 100.0) / 100.0;

                //Get amount dime used by dividing, then getting the left over amount for next calculation, then resetting the format of the amount.
                dime = (int) (moneyAmount/0.10);
                moneyAmount = moneyAmount - 0.10 * dime;
                moneyAmount = Math.round(moneyAmount * 100.0) / 100.0;

                //Get amount nickel used by dividing, then getting the left over amount for next calculation, then resetting the format of the amount.
                nickel = (int) (moneyAmount/0.05);
                moneyAmount = moneyAmount - 0.05 * nickel;
                moneyAmount = Math.round(moneyAmount * 100.0) / 100.0;

                //Get amount penny used by dividing, then getting the left over amount for next calculation, then resetting the format of the amount.
                penny = (int) (moneyAmount/0.01);

                //Have to cast all variable to string because set text looks for string and variables are integers
                txtfieldPennies.setText(Integer.toString(penny));
                txtfieldQuarters.setText(Integer.toString(quarter));
                txtfieldNickels.setText(Integer.toString(nickel));
                txtfieldLoonies.setText(Integer.toString(loonie));
                txtfieldDimes.setText(Integer.toString(dime));
                txtfieldToonies.setText(Integer.toString(toonie));
                //Clears the enter currency text field for easier user access
                txtfieldEnterCurrency.setText("         ");
            }
            else {
                txtfieldAmount.setText("Format Invalid");
            }
        }
        catch (Exception e) {
            txtfieldAmount.setText("Amount Invalid");
        }
    }//GEN-LAST:event_buttonCalculateActionPerformed

    private void txtfieldEnterCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldEnterCurrencyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldEnterCurrencyActionPerformed

    private void txtfieldAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldAmountActionPerformed

    private void txtfieldLooniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldLooniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldLooniesActionPerformed

    private void txtfieldTooniesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfieldTooniesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfieldTooniesActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        // TODO add your handling code here:
        //Ends the program once clicked.
        System.exit(0);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonSiwtchtoFrame2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSiwtchtoFrame2ActionPerformed
        // TODO add your handling code here:
        Frame2 myFrame1 = new Frame2();
        myFrame1.setVisible((true));
    }//GEN-LAST:event_buttonSiwtchtoFrame2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(U1A1_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(U1A1_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(U1A1_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(U1A1_EdmondLiang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new U1A1_EdmondLiang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton buttonCalculate;
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonSiwtchtoFrame2;
    private javax.swing.JLabel lblDimes;
    private javax.swing.JLabel lblEnterCurrency;
    private javax.swing.JLabel lblFormat;
    private javax.swing.JLabel lblLoonies;
    private javax.swing.JLabel lblNickels;
    private javax.swing.JLabel lblPennies;
    private javax.swing.JLabel lblQuaters;
    private javax.swing.JLabel lblToonies;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField txtfieldAmount;
    private javax.swing.JTextField txtfieldDimes;
    private javax.swing.JTextField txtfieldEnterCurrency;
    private javax.swing.JTextField txtfieldLoonies;
    private javax.swing.JTextField txtfieldNickels;
    private javax.swing.JTextField txtfieldPennies;
    private javax.swing.JTextField txtfieldQuarters;
    private javax.swing.JTextField txtfieldToonies;
    // End of variables declaration//GEN-END:variables
}
